GET http://localhost:9000/user-api/users

###
GET http://localhost:9000/user-api/users/69aa765dd30060f8f00abcd0



### reate new User

POST http://localhost:9000/user-api/users
content-Type: application/json

{
    "username":"tO",
    "password":"machli..",
    "email":"tOOny@mail.com",
    "age":20
} 

###
PUT http://localhost:9000/user-api/users
Content-Type: application/json

{
    "username":"Bhu",
    "password":"bhanu",
    "email":"bhanu@mail.com"
    
} 
###
DELETE http://localhost:9000/user-api/users/69aa765dd30060f8f00abcd0
